services:
  - type: web
    name: covid-predictor-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false 